### ISSUE TITLE
Please allow building with GHC 8.4.1 (base-4.11.0.0, template-haskell-2.13.0.0)

### ISSUE THREAD

**Issue by peti** [frerich/catamorphism#7]
The build seems to work fine when the constraints on `base` and `template-haskell` are relaxed.

**Comment by frerich** [comment]
I'm not on GHC 8.4.1 yet, and it appears that Travis CI doesn't have GHC 8.4.1 installed either. I could do a blind patch to update the dependencies, but I'd feel a lot better if I knew that the CI system does the building & testing for me. I'll wait a bit for the Travis guys to catch up, maybe it won't be long.
